services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - ./staticfiles:/app/staticfiles
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - nginx_network
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge