# Generated by Django 5.2.4 on 2025-08-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bensryaa', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_input_label',
            field=models.CharField(blank=True, help_text='Opsional: ganti label input untuk tipe custom', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_input_type',
            field=models.CharField(choices=[('none', 'Tidak Ada'), ('game_id_server', 'User ID + Server ID'), ('phone_number', 'Nomor HP'), ('email', 'Email'), ('custom', 'Custom Text')], default='none', max_length=20),
        ),
    ]
