# Generated by Django 5.2.4 on 2025-08-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bensryaa', '0006_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
