# Generated by Django 5.2.4 on 2025-08-14 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bensryaa', '0008_emailotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
