# Generated by Django 5.2.5 on 2025-09-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bensryaa', '0011_product_desc_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
