# Generated by Django 5.2.5 on 2025-09-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bensryaa', '0013_product_category_alter_product_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
