# Generated by Django 5.2.5 on 2025-09-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bensryaa', '0014_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
